"""create <table> table

Revision ID: 09118915a123
Revises: e56d3bc0e337
Create Date: 2026-08-04 11:46:04.499286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09118915a123'
down_revision: Union[str, Sequence[str], None] = 'e56d3bc0e337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_balances',
    sa.Column('stock_balance_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('stock_balance_id'),
    sa.UniqueConstraint('organization_id', 'warehouse_id', 'product_id', name='uq_stock_balance_org_wh_product'),
    comment='Current stock balance for each product in each warehouse.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_balances')
    # ### end Alembic commands ###
