"""create products table

Revision ID: 50158d3b4217
Revises: 728abd923de4
Create Date: 2026-08-03 16:18:02.819238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50158d3b4217'
down_revision: Union[str, Sequence[str], None] = '728abd923de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('organization_id', 'product_code', name='uq_product_org_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
