"""empty message

Revision ID: 6134485516af
Revises: 248ed5867426
Create Date: 2026-08-04 16:33:25.396436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6134485516af'
down_revision: Union[str, Sequence[str], None] = '248ed5867426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order_items',
    sa.Column('production_order_item_id', sa.UUID(), nullable=False),
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('produced_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.production_order_id'], ),
    sa.PrimaryKeyConstraint('production_order_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_order_items')
    # ### end Alembic commands ###
