"""create reasons table

Revision ID: 728abd923de4
Revises: 1e19639f2bc8
Create Date: 2026-08-03 15:52:02.147779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728abd923de4'
down_revision: Union[str, Sequence[str], None] = '1e19639f2bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reason_org_name_type', 'reasons', ['organization_id', 'reason_name', 'reason_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reason_org_name_type', 'reasons', type_='unique')
    # ### end Alembic commands ###
