"""Update user authentication fields

Revision ID: 7ce9704b06bc
Revises: 2da8faf19d31
Create Date: 2026-08-03 02:19:00.067186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce9704b06bc'
down_revision: Union[str, Sequence[str], None] = '2da8faf19d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_user_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'users', ['supabase_user_uuid'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'supabase_user_uuid')
    # ### end Alembic commands ###
