"""create bom items table

Revision ID: a2dbfe7d96b2
Revises: 6df2d50a39ce
Create Date: 2026-08-04 11:21:54.660719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2dbfe7d96b2'
down_revision: Union[str, Sequence[str], None] = '6df2d50a39ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_items',
    sa.Column('bom_item_id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_product_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('waste_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.bom_id'], ),
    sa.ForeignKeyConstraint(['ingredient_product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('bom_item_id'),
    comment='Ingredients for each Bill of Materials (recipe). Each record represents one ingredient required to produce a finished product.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom_items')
    # ### end Alembic commands ###
